version: 1
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    working_directory: /build
    steps:
      - checkout
      - run:
          name: Build solution
          command: dotnet build src
      - store_artifacts:
          path: /build
  test:
    docker:
      - image: microsoft/dotnet:sdk
    working_directory: /build
    steps:
      - run:
          name: Tests
          command: dotnet test -v normal --no-build --no-restore src/**/*.Tests.csproj
workflows:
  version: 1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build