version: 1
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Build solution
          command: dotnet build src
      - persist_to_workspace:
          root: /
  test:
    working_directory: ~/build
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Tests
          command: dotnet test -v normal --no-build --no-restore src/**/*.Tests.csproj
workflows:
  version: 1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build