version: 1
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build src
      - run:
          name: Tests
          command: dotnet test -v normal --no-build --no-restore src/**/*.Tests.csproj