version: 1
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Build solution
          command: dotnet build src
      - persist_to_workspace:
          root: .
          paths: 
            - src/*
  test:
    working_directory: ~/build
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Tests
          command: dotnet test -v normal --no-build src/**/*.Tests.csproj
    post:
      - bash <(curl -s https://codecov.io/bash) -t 32266071-966d-40e1-963c-2aed09047656
workflows:
  version: 1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build